### ISSUE TITLE
Issue if no Item in DynamoDB

### ISSUE THREAD

**Issue by igordavid** [tangerinedream/AWS_EC2_Scheduler#4]
If there is no item TierScaling defined in DynamoDB, "-p" flag can't be used.

Error message:

Traceback (most recent call last):
  File "/home/scheduler/AWS_EC2_Scheduler/current/Orchestrator.py", line 786, in <module>
    orchMain.orchestrate(action)
  File "/home/scheduler/AWS_EC2_Scheduler/current/Orchestrator.py", line 563, in orchestrate
    self.startATier(currTier)
  File "/home/scheduler/AWS_EC2_Scheduler/current/Orchestrator.py", line 655, in startATier
    instanceTypeToLaunch = self.isScalingAction(tierName)
  File "/home/scheduler/AWS_EC2_Scheduler/current/Orchestrator.py", line 676, in isScalingAction
    scalingDict = tierAttributes[ Orchestrator.TIER_SCALING ]
KeyError: 'TierScaling'

**Comment by tangerinedream** [comment]
Thanks for identifying that bug, which is now fixed in version 0.19
